### ISSUE TITLE
Worst Logger ever

### ISSUE THREAD

**Issue by PhoenixDuhh** [glitch65/Discord-Five-nuker-bot#1]
This is the worst covered logger I've ever seen.

You need to cover it. You have a .py file in the code but, a executable in the release?

**Comment by glitch65** [comment]
> This is the worst covered logger I've ever seen.
> 
> You need to cover it. You have a .py file in the code but, a executable in the release?

I made an exe file so that it would be more convenient for people to download, so as not to download Python and also install libraries for them, by the way, beginners get confused in this. And no, this is not a malware or a stealer

**Comment by glitch65** [comment]
> This is the worst covered logger I've ever seen.
> 
> You need to cover it. You have a .py file in the code but, a executable in the release?

I made an exe file so that it would be more convenient for people to download, so as not to download Python and also install libraries for them, by the way, beginners get confused in this. And no, this is not a malware or a stealer

**Comment by 0x3C50** [comment]
can confirm, the exe contains the same code as the py says it has

although @glitch65 the reason for packaging it inside an exe is stupid at best, just distributing a raw python file is more convenient
